"""
v2_simulation Notebook 构建脚本
运行此脚本生成完整的 v2_simulation.ipynb
"""
import json
import os

def md(lines):
    """创建 Markdown cell"""
    if isinstance(lines, str):
        lines = [lines]
    return {"cell_type": "markdown", "metadata": {}, "source": lines}

def code(lines):
    """创建 Code cell"""
    if isinstance(lines, str):
        lines = [lines]
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": lines}

notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {"provenance": [], "toc_visible": True},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"}
    },
    "cells": []
}

cells = notebook["cells"]

# =====================================================================
# Title
# =====================================================================
cells.append(md([
    "# v2 固定位置模式仿真笔记本\n",
    "\n",
    "本笔记本模拟手术机器人器械护士助手的 **v2 固定位置模式**，在无硬件环境下验证核心逻辑、可视化机械臂轨迹、并提供端到端流程演示。\n",
    "\n",
    "### v1 vs v2 核心区别\n",
    "\n",
    "| | v1 (当前) | v2 (固定位置模式) |\n",
    "|---|---|---|\n",
    "| 定位方式 | YOLO检测 + 手眼标定 | 固定槽位 + 示教坐标查表 |\n",
    "| 依赖 | 摄像头、YOLO模型、标定矩阵 | instruments.ini 配置文件 |\n",
    "| 耗时 | 标定1小时 + 识别延迟 | 示教5分钟，运行零延迟 |\n",
    "| 稳定性 | 受光照/摆放影响大 | 坐标固定，完全可复现 |\n",
    "\n",
    "### 笔记本结构\n",
    "- **Part 1** (Cell 2-6): v2 核心逻辑验证\n",
    "- **Part 2** (Cell 7-10): 3D 轨迹可视化\n",
    "- **Part 3** (Cell 11-15): 端到端流程演示"
]))

# =====================================================================
# Cell 1: 环境初始化
# =====================================================================
cells.append(md([
    "## Cell 1: 环境初始化与全局常量\n",
    "\n",
    "所有常量均直接提取自生产代码 `robotConfig.ini`、`Constants.py`、`gripper_config.py`。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 1: 环境初始化\n",
    "# ============================================================\n",
    "import configparser\n",
    "import ast\n",
    "import io\n",
    "import math\n",
    "import time\n",
    "from dataclasses import dataclass, field\n",
    "from typing import Dict, List, Optional, Tuple\n",
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from mpl_toolkits.mplot3d import Axes3D\n",
    "from mpl_toolkits.mplot3d.art3d import Poly3DCollection\n",
    "\n",
    "# ---------- 全局常量 (来源: robotConfig.ini) ----------\n",
    "TARGET_POINT = [0, -50.2, -67.3, 112.5, 90, -90, 1]    # 递送目标位置 (关节模式)\n",
    "RESET_POINT = [0, 32.6, -129.1, 6.7, 90, -90, 1]       # 初始/复位位置 (关节模式)\n",
    "\n",
    "# ---------- 运动参数 (来源: RobotController.robotMove()) ----------\n",
    "Z_HOVER = 150    # mm, 悬停高度偏移\n",
    "Z_GRASP = 1      # mm, 抓取高度偏移\n",
    "FIXED_RX = -180  # 度, 固定X轴旋转 (末端朝下)\n",
    "FIXED_RY = 0     # 度, 固定Y轴旋转\n",
    "\n",
    "# ---------- 器械映射 (来源: Constants.py) ----------\n",
    "INSTRUMENT_MAP = {\"0\": \"刀柄\", \"1\": \"镊子\", \"2\": \"剪刀\", \"3\": \"持针钳\"}\n",
    "\n",
    "# ---------- 夹爪预设 (来源: gripper_config.py) ----------\n",
    "GRIPPER_PRESETS = {\n",
    "    -1: {\"open\": 800, \"close\": 20, \"force\": 800},\n",
    "     0: {\"open\": 400, \"close\": 20, \"force\": 800},\n",
    "     1: {\"open\": 600, \"close\": 10, \"force\": 980},\n",
    "     2: {\"open\": 500, \"close\": 40, \"force\": 550},\n",
    "     3: {\"open\": 500, \"close\": 10, \"force\": 800},\n",
    "}\n",
    "\n",
    "# ---------- 手眼标定矩阵 (来源: RobotCalibrateUtil.py, 用于 v1 对比) ----------\n",
    "R1 = np.array([[-9.99801479e-01, 1.99246458e-02, 1.09910175e-04],\n",
    "               [ 1.99247862e-02, 9.99800396e-01, 1.47357936e-03],\n",
    "               [-8.05276895e-05, 1.47547676e-03,-9.99998908e-01]])\n",
    "T1 = np.array([[318.67681045], [-1074.33196951], [-44.34858293]])\n",
    "k1 = 1.2498330321889395\n",
    "\n",
    "print(\"环境初始化完成\")\n",
    "print(f\"复位点(关节): {RESET_POINT}\")\n",
    "print(f\"递送点(关节): {TARGET_POINT}\")\n",
    "print(f\"器械种类: {list(INSTRUMENT_MAP.values())}\")"
]))

# =====================================================================
# Part 1: 核心逻辑验证
# =====================================================================
cells.append(md([
    "---\n",
    "# Part 1: v2 核心逻辑验证\n",
    "\n",
    "## Cell 2: instruments.ini 配置格式与加载\n",
    "\n",
    "v2 的核心配置文件。每种器械对应一个固定槽位，记录:\n",
    "- 机械臂笛卡尔坐标 `[x, y, z, rz]` (mm/度)\n",
    "- 夹爪参数 `{open, close, force}`\n",
    "\n",
    "坐标范围参考手眼标定 B 矩阵的实际样本值 (X:-450~70, Y:-800~-530, Z:-50~-48)。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 2: instruments.ini 配置格式定义与加载\n",
    "# 对标: Constants.init() + configparser 读取 robotConfig.ini\n",
    "# ============================================================\n",
    "\n",
    "INSTRUMENTS_INI_CONTENT = \"\"\"\n",
    "[mode]\n",
    "locate_mode = fixed\n",
    "\n",
    "[instruments]\n",
    "mapping = {\"0\": \"刀柄\", \"1\": \"镊子\", \"2\": \"剪刀\", \"3\": \"持针钳\"}\n",
    "\n",
    "[positions]\n",
    "; 格式: [x, y, z, rz]  笛卡尔坐标(mm) + 末端偏转角(度)\n",
    "; 坐标来源: 示教工具(teach_tool.py)录入\n",
    "0 = [-350.0, -600.0, -48.5, 45.0]\n",
    "1 = [-200.0, -650.0, -48.0, 30.0]\n",
    "2 = [-100.0, -700.0, -49.0, 60.0]\n",
    "3 = [50.0, -580.0, -48.8, 15.0]\n",
    "\n",
    "[gripper]\n",
    "0 = {\"open\": 400, \"close\": 20, \"force\": 800}\n",
    "1 = {\"open\": 600, \"close\": 10, \"force\": 980}\n",
    "2 = {\"open\": 500, \"close\": 40, \"force\": 550}\n",
    "3 = {\"open\": 500, \"close\": 10, \"force\": 800}\n",
    "\"\"\"\n",
    "\n",
    "@dataclass\n",
    "class InstrumentConfig:\n",
    "    \"\"\"单个器械的完整配置\"\"\"\n",
    "    id: int\n",
    "    name: str\n",
    "    x: float\n",
    "    y: float\n",
    "    z: float\n",
    "    rz: float\n",
    "    gripper: dict\n",
    "\n",
    "\n",
    "class ConfigLoader:\n",
    "    \"\"\"加载 instruments.ini 配置文件\n",
    "\n",
    "    对标: Constants.init() 使用 configparser 读取 robotConfig.ini\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, ini_content: str):\n",
    "        self._config = configparser.ConfigParser()\n",
    "        self._config.read_string(ini_content)\n",
    "        self._mapping = ast.literal_eval(self._config.get('instruments', 'mapping'))\n",
    "        self._instruments = {}\n",
    "        self._load_all()\n",
    "\n",
    "    def _load_all(self):\n",
    "        for str_id, name in self._mapping.items():\n",
    "            int_id = int(str_id)\n",
    "            pos = ast.literal_eval(self._config.get('positions', str_id))\n",
    "            grip = ast.literal_eval(self._config.get('gripper', str_id))\n",
    "            self._instruments[int_id] = InstrumentConfig(\n",
    "                id=int_id, name=name,\n",
    "                x=pos[0], y=pos[1], z=pos[2], rz=pos[3],\n",
    "                gripper=grip\n",
    "            )\n",
    "\n",
    "    def get_mode(self) -> str:\n",
    "        return self._config.get('mode', 'locate_mode')\n",
    "\n",
    "    def get_instrument(self, instrument_id: int) -> InstrumentConfig:\n",
    "        if instrument_id not in self._instruments:\n",
    "            raise ValueError(f'未知器械ID: {instrument_id}')\n",
    "        return self._instruments[instrument_id]\n",
    "\n",
    "    def get_all(self) -> Dict[int, InstrumentConfig]:\n",
    "        return dict(self._instruments)\n",
    "\n",
    "    def get_name_to_id(self) -> Dict[str, int]:\n",
    "        return {v.name: v.id for v in self._instruments.values()}\n",
    "\n",
    "\n",
    "# --- 验证加载 ---\n",
    "config_loader = ConfigLoader(INSTRUMENTS_INI_CONTENT)\n",
    "print(f'定位模式: {config_loader.get_mode()}')\n",
    "print(f'器械数量: {len(config_loader.get_all())}')\n",
    "print(f'名称->ID映射: {config_loader.get_name_to_id()}')\n",
    "print()\n",
    "for inst_id, inst in config_loader.get_all().items():\n",
    "    print(f'  槽位{inst_id} [{inst.name}]: '\n",
    "          f'位置=({inst.x}, {inst.y}, {inst.z}) rz={inst.rz}  '\n",
    "          f'夹爪=open:{inst.gripper[\"open\"]} force:{inst.gripper[\"force\"]}')"
]))

# Cell 3: MockLLMService
cells.append(md([
    "## Cell 3: MockLLMService（文本解析）\n",
    "\n",
    "对标: `LLMService.processCmdText()` — 当前实际上是关键词匹配，v2 增加别名支持。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 3: MockLLMService\n",
    "# 对标: bitRobot/service/llm/LLMService.py\n",
    "# ============================================================\n",
    "\n",
    "class MockLLMService:\n",
    "    \"\"\"语音文本解析服务\n",
    "\n",
    "    对标: LLMService.processCmdText()\n",
    "    v1: 精确关键词匹配\n",
    "    v2: 增加别名和模糊匹配\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, config_loader: ConfigLoader):\n",
    "        self._name_to_id = config_loader.get_name_to_id()\n",
    "\n",
    "    def process_cmd_text(self, text: str):\n",
    "        \"\"\"解析语音文本，返回任务类型和器械ID\n",
    "\n",
    "        返回值格式与真实 LLMService 完全一致:\n",
    "        - 字符串 '统计'/'清点'/'取消'\n",
    "        - 元组 ('器件', id)  其中 id=-1 表示未识别\n",
    "        \"\"\"\n",
    "        if '统计' in text:\n",
    "            return '统计'\n",
    "        elif '清点' in text:\n",
    "            return '清点'\n",
    "        elif '取消' in text:\n",
    "            return '取消'\n",
    "\n",
    "        for name, inst_id in self._name_to_id.items():\n",
    "            if name in text:\n",
    "                return ('器件', inst_id)\n",
    "\n",
    "        return ('器件', -1)\n",
    "\n",
    "\n",
    "# --- 验证 ---\n",
    "llm = MockLLMService(config_loader)\n",
    "test_inputs = ['请传递镊子', '给我剪刀', '拿刀柄', '持针钳', '统计', '清点', '取消', '你好']\n",
    "print('文本解析测试:')\n",
    "for text in test_inputs:\n",
    "    result = llm.process_cmd_text(text)\n",
    "    print(f\"  '{text}' -> {result}\")"
]))

# Cell 4: PositionResolver
cells.append(md([
    "## Cell 4: PositionResolver（固定位置查表器）\n",
    "\n",
    "**v2 的核心替换点**: 用配置文件查表替代 `YOLOService.identifyObj()` + `HandEyeService.transform()` 整条链路。\n",
    "\n",
    "同时提供 `HandEyeResolver` 用于对比 v1 路径。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 4: PositionResolver\n",
    "# 替代: YOLOService.identifyObj() + HandEyeService.transform()\n",
    "# ============================================================\n",
    "\n",
    "class PositionResolver:\n",
    "    \"\"\"v2 固定位置查表器\n",
    "\n",
    "    替代 v1 的 YOLO + 手眼标定两步:\n",
    "    - v1: 像素坐标 -> HandEyeService.transform() -> 机械臂坐标\n",
    "    - v2: 器械ID -> ConfigLoader.get_instrument() -> 机械臂坐标(直接)\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, config_loader: ConfigLoader):\n",
    "        self._config = config_loader\n",
    "\n",
    "    def resolve(self, instrument_id: int) -> dict:\n",
    "        \"\"\"查表获取器械的机械臂坐标和夹爪参数\"\"\"\n",
    "        inst = self._config.get_instrument(instrument_id)\n",
    "        return {\n",
    "            'x': inst.x, 'y': inst.y, 'z': inst.z,\n",
    "            'rz': inst.rz,\n",
    "            'gripper': inst.gripper,\n",
    "            'name': inst.name,\n",
    "        }\n",
    "\n",
    "\n",
    "class HandEyeResolver:\n",
    "    \"\"\"v1 手眼标定坐标转换 (仅用于对比演示)\n",
    "\n",
    "    对标: HandEyeService.transform() + RobotCalibrateUtil.transfer()\n",
    "    公式: B = k * (R @ A) + T\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        self.R = R1\n",
    "        self.T = T1\n",
    "        self.k = k1\n",
    "\n",
    "    def resolve(self, pixel_x: float, pixel_y: float, cam_id: int = 1) -> dict:\n",
    "        A = np.array([[pixel_x], [pixel_y], [0]])\n",
    "        B = self.k * (self.R @ A) + self.T\n",
    "        coords = B.flatten().tolist()\n",
    "        return {'x': round(coords[0], 2), 'y': round(coords[1], 2), 'z': round(coords[2], 2)}\n",
    "\n",
    "\n",
    "# --- 对比演示 ---\n",
    "resolver_v2 = PositionResolver(config_loader)\n",
    "resolver_v1 = HandEyeResolver()\n",
    "\n",
    "print('=== v1 vs v2 坐标获取对比 ===')\n",
    "print()\n",
    "print('v2 (查表, 直接获取):')\n",
    "for i in range(4):\n",
    "    pos = resolver_v2.resolve(i)\n",
    "    print(f\"  {pos['name']}: ({pos['x']}, {pos['y']}, {pos['z']}) rz={pos['rz']}\")\n",
    "\n",
    "print()\n",
    "print('v1 (假设像素坐标 -> 手眼标定转换):')\n",
    "fake_pixels = [(400, 350), (300, 400), (250, 300), (200, 380)]\n",
    "for i, (px, py) in enumerate(fake_pixels):\n",
    "    pos = resolver_v1.resolve(px, py)\n",
    "    name = INSTRUMENT_MAP[str(i)]\n",
    "    print(f\"  {name}: 像素({px},{py}) -> 标定 -> ({pos['x']}, {pos['y']}, {pos['z']})\")\n",
    "\n",
    "print()\n",
    "print('结论: v2 跳过了 YOLO 检测和手眼标定，直接从配置读取精确坐标')"
]))

# Cell 5: TaskRouter
cells.append(md([
    "## Cell 5: TaskRouter（任务路由）\n",
    "\n",
    "对标 `TaskController` 的 `llmRun()` + `run()` 双线程逻辑，简化为同步调用。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 5: TaskRouter\n",
    "# 对标: BaseTaskHandler.TaskController (llmRun + run)\n",
    "# ============================================================\n",
    "\n",
    "@dataclass\n",
    "class TaskInfo:\n",
    "    \"\"\"任务信息 (对标: BaseTaskHandler.TaskInfo)\"\"\"\n",
    "    msg_header: str   # '器件'/'统计'/'清点'/'取消'\n",
    "    id: int           # 器械ID, -1表示无关\n",
    "\n",
    "\n",
    "class TaskRouter:\n",
    "    \"\"\"任务路由调度\n",
    "\n",
    "    对标: TaskController 的 llmRun() 解析 + run() 路由\n",
    "    简化为同步调用（去掉线程循环和时间过期检查）\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, llm: MockLLMService, resolver: PositionResolver):\n",
    "        self._llm = llm\n",
    "        self._resolver = resolver\n",
    "\n",
    "    def process_voice(self, voice_text: str) -> TaskInfo:\n",
    "        \"\"\"语音文本 -> TaskInfo\"\"\"\n",
    "        result = self._llm.process_cmd_text(voice_text)\n",
    "        if isinstance(result, str):\n",
    "            return TaskInfo(msg_header=result, id=-1)\n",
    "        else:\n",
    "            return TaskInfo(msg_header=result[0], id=result[1])\n",
    "\n",
    "    def dispatch(self, task: TaskInfo) -> dict:\n",
    "        \"\"\"任务分发\"\"\"\n",
    "        if task.msg_header == '器件':\n",
    "            if task.id == -1:\n",
    "                return {'status': 'rejected', 'reason': '未识别到器械名称'}\n",
    "            pos = self._resolver.resolve(task.id)\n",
    "            return {'status': 'dispatched', 'handler': 'RobotController', 'position': pos}\n",
    "        elif task.msg_header in ('统计', '清点'):\n",
    "            return {'status': 'dispatched', 'handler': 'CountTaskHandler', 'action': task.msg_header}\n",
    "        elif task.msg_header == '取消':\n",
    "            return {'status': 'dispatched', 'handler': 'CancelMove', 'action': '取消'}\n",
    "        else:\n",
    "            return {'status': 'error', 'reason': f'未知指令: {task.msg_header}'}\n",
    "\n",
    "\n",
    "# --- 验证 ---\n",
    "router = TaskRouter(llm, resolver_v2)\n",
    "print('任务路由测试:')\n",
    "for text in ['传递镊子', '给我剪刀', '统计', '取消', '你好']:\n",
    "    task = router.process_voice(text)\n",
    "    result = router.dispatch(task)\n",
    "    print(f\"  '{text}' -> task({task.msg_header}, id={task.id}) -> {result['status']}\")\n",
    "    if result['status'] == 'dispatched' and 'position' in result:\n",
    "        p = result['position']\n",
    "        print(f\"    坐标: ({p['x']}, {p['y']}, {p['z']}) rz={p['rz']}\")"
]))

# Cell 6: 测试
cells.append(md([
    "## Cell 6: 核心链路验证测试\n",
    "\n",
    "串联所有组件，验证 v2 核心链路: **语音 -> 解析 -> 查表 -> 坐标**"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 6: 核心链路验证测试\n",
    "# ============================================================\n",
    "\n",
    "def run_core_tests(router: TaskRouter):\n",
    "    test_cases = [\n",
    "        ('请传递刀柄',   '器件', 0, 'dispatched'),\n",
    "        ('给我镊子',     '器件', 1, 'dispatched'),\n",
    "        ('拿剪刀过来',   '器件', 2, 'dispatched'),\n",
    "        ('持针钳',       '器件', 3, 'dispatched'),\n",
    "        ('统计',         '统计', -1, 'dispatched'),\n",
    "        ('清点一下',     '清点', -1, 'dispatched'),\n",
    "        ('取消操作',     '取消', -1, 'dispatched'),\n",
    "        ('你好',         '器件', -1, 'rejected'),\n",
    "        ('天气怎么样',   '器件', -1, 'rejected'),\n",
    "    ]\n",
    "\n",
    "    print(f'{\"输入\":<14} {\"解析\":<8} {\"ID\":>3}  {\"状态\":<10} {\"坐标/说明\"}')\n",
    "    print('-' * 75)\n",
    "\n",
    "    passed = 0\n",
    "    for text, exp_header, exp_id, exp_status in test_cases:\n",
    "        task = router.process_voice(text)\n",
    "        result = router.dispatch(task)\n",
    "\n",
    "        ok = (task.msg_header == exp_header and task.id == exp_id\n",
    "              and result['status'] == exp_status)\n",
    "        if ok:\n",
    "            passed += 1\n",
    "\n",
    "        mark = 'PASS' if ok else 'FAIL'\n",
    "        detail = ''\n",
    "        if 'position' in result:\n",
    "            p = result['position']\n",
    "            detail = f\"({p['x']}, {p['y']}, {p['z']}) rz={p['rz']}\"\n",
    "        elif 'reason' in result:\n",
    "            detail = result['reason']\n",
    "        elif 'action' in result:\n",
    "            detail = result['action']\n",
    "\n",
    "        print(f'{text:<14} {task.msg_header:<8} {task.id:>3}  {mark:<10} {detail}')\n",
    "\n",
    "    print('-' * 75)\n",
    "    print(f'测试结果: {passed}/{len(test_cases)} 通过')\n",
    "\n",
    "run_core_tests(router)"
]))

# =====================================================================
# Part 2: 3D 轨迹
# =====================================================================
cells.append(md([
    "---\n",
    "# Part 2: 3D 轨迹可视化\n",
    "\n",
    "## Cell 7: MockRobotArm（轨迹记录器）\n",
    "\n",
    "模拟 `RobotControlModule`，不发送真实指令，只记录轨迹点。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 7: MockRobotArm\n",
    "# 对标: bitRobot/service/robot_control/controller.py\n",
    "# ============================================================\n",
    "\n",
    "@dataclass\n",
    "class TrajectoryPoint:\n",
    "    raw_point: list\n",
    "    mode: int\n",
    "    label: str = ''\n",
    "    phase: str = ''\n",
    "    action: str = ''\n",
    "\n",
    "\n",
    "class MockRobotArm:\n",
    "    \"\"\"模拟机械臂, 记录轨迹\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        self.trajectory: List[TrajectoryPoint] = []\n",
    "        self.gripper_state = 'open'\n",
    "        self._current_phase = ''\n",
    "        self._current_label = ''\n",
    "\n",
    "    def set_phase(self, phase: str, label: str = ''):\n",
    "        self._current_phase = phase\n",
    "        self._current_label = label\n",
    "\n",
    "    def execute_path(self, path: list) -> dict:\n",
    "        for i, point in enumerate(path):\n",
    "            tp = TrajectoryPoint(\n",
    "                raw_point=list(point), mode=int(point[6]),\n",
    "                phase=self._current_phase, label=self._current_label,\n",
    "            )\n",
    "            self.trajectory.append(tp)\n",
    "        return {'status': 'queued', 'count': len(path)}\n",
    "\n",
    "    def open_gripper(self, preset_id: int):\n",
    "        self.gripper_state = 'open'\n",
    "        if self.trajectory:\n",
    "            self.trajectory[-1].action = f'open_gripper({preset_id})'\n",
    "\n",
    "    def close_gripper(self, preset_id: int):\n",
    "        self.gripper_state = 'closed'\n",
    "        if self.trajectory:\n",
    "            self.trajectory[-1].action = f'close_gripper({preset_id})'\n",
    "\n",
    "    def is_moving(self) -> bool:\n",
    "        return False\n",
    "\n",
    "    def get_trajectory(self) -> List[TrajectoryPoint]:\n",
    "        return list(self.trajectory)\n",
    "\n",
    "    def clear_trajectory(self):\n",
    "        self.trajectory.clear()\n",
    "\n",
    "print('MockRobotArm 已定义')"
]))

# Cell 8: FK
cells.append(md([
    "## Cell 8: 前向运动学估算 (joint -> cartesian)\n",
    "\n",
    "RESET_POINT 和 TARGET_POINT 使用关节角度(mode=1)，但 3D 可视化需要笛卡尔坐标。\n",
    "\n",
    "> **注意**: 估算坐标仅用于可视化教学，不代表真实机器人的精确位置。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 8: 前向运动学估算\n",
    "# ============================================================\n",
    "\n",
    "JOINT_TO_CARTESIAN_MAP = {\n",
    "    tuple(RESET_POINT[:6]):  (0, -350, 350),     # 机械臂收拢, 末端在上方偏后\n",
    "    tuple(TARGET_POINT[:6]): (300, -100, 200),    # 末端伸向前方递送区\n",
    "    (4.5, 22.6, -134.2, 22.6, 90, 10.4): (10, -380, 380),  # 碰撞恢复点\n",
    "}\n",
    "\n",
    "\n",
    "def point_to_cartesian(point: list) -> Tuple[float, float, float]:\n",
    "    \"\"\"将7元素路径点转换为笛卡尔坐标 (x, y, z)\"\"\"\n",
    "    mode = int(point[6])\n",
    "    if mode == 0:\n",
    "        return (point[0], point[1], point[2])\n",
    "    else:\n",
    "        key = tuple(point[:6])\n",
    "        if key in JOINT_TO_CARTESIAN_MAP:\n",
    "            return JOINT_TO_CARTESIAN_MAP[key]\n",
    "        return (point[0] * 5, point[1] * 5, 200)\n",
    "\n",
    "\n",
    "print('关节->笛卡尔转换验证:')\n",
    "print(f'  RESET_POINT  -> {point_to_cartesian(RESET_POINT)}')\n",
    "print(f'  TARGET_POINT -> {point_to_cartesian(TARGET_POINT)}')\n",
    "print(f'  笛卡尔示例  -> {point_to_cartesian([-350, -600, 101.5, -180, 0, 45, 0])}')"
]))

# Cell 9: 轨迹生成
cells.append(md([
    "## Cell 9: 完整拾取-递送轨迹生成\n",
    "\n",
    "精确复刻 `RobotController.robotMove()` 的 3 阶段运动序列。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 9: 轨迹生成\n",
    "# 精确对标: RobotController.robotMove() 的 3 阶段\n",
    "# ============================================================\n",
    "\n",
    "def generate_full_trajectory(instrument_id: int, resolver: PositionResolver) -> List[TrajectoryPoint]:\n",
    "    \"\"\"生成一个完整的拾取-递送轨迹\"\"\"\n",
    "    pos = resolver.resolve(instrument_id)\n",
    "    x, y, z, rz = pos['x'], pos['y'], pos['z'], pos['rz']\n",
    "\n",
    "    arm = MockRobotArm()\n",
    "\n",
    "    # 起始: 预备姿态\n",
    "    arm.set_phase('idle', '起始(复位)')\n",
    "    arm.execute_path([RESET_POINT])\n",
    "\n",
    "    # 阶段1: 接近抓取 (对标 robotMove line 72-75)\n",
    "    arm.set_phase('approach', '悬停')\n",
    "    arm.execute_path([[x, y, z + Z_HOVER, FIXED_RX, FIXED_RY, rz, 0]])\n",
    "    arm.set_phase('grasp', '抓取')\n",
    "    arm.execute_path([[x, y, z + Z_GRASP, FIXED_RX, FIXED_RY, rz, 0]])\n",
    "    arm.close_gripper(instrument_id)\n",
    "\n",
    "    # 阶段2: 提升递送 (对标 robotMove line 104)\n",
    "    arm.set_phase('lift', '提升')\n",
    "    arm.execute_path([[x, y, z + Z_HOVER, FIXED_RX, FIXED_RY, rz, 0]])\n",
    "    arm.set_phase('transit', '过渡(复位)')\n",
    "    arm.execute_path([RESET_POINT])\n",
    "    arm.set_phase('deliver', '递送')\n",
    "    arm.execute_path([TARGET_POINT])\n",
    "\n",
    "    # 阶段3: 力检测后返回 (对标 robotMove line 145)\n",
    "    arm.set_phase('return', '最终复位')\n",
    "    arm.open_gripper(-1)\n",
    "    arm.execute_path([RESET_POINT])\n",
    "\n",
    "    return arm.get_trajectory()\n",
    "\n",
    "\n",
    "traj = generate_full_trajectory(1, resolver_v2)\n",
    "print(f'镊子完整轨迹 ({len(traj)} 个路径点):')\n",
    "for i, tp in enumerate(traj):\n",
    "    cart = point_to_cartesian(tp.raw_point)\n",
    "    mode_str = '笛卡尔' if tp.mode == 0 else '关节'\n",
    "    action_str = f' [{tp.action}]' if tp.action else ''\n",
    "    print(f'  {i}: [{tp.phase}] {tp.label} -> '\n",
    "          f'3D({cart[0]:.0f}, {cart[1]:.0f}, {cart[2]:.0f}) '\n",
    "          f'mode={mode_str}{action_str}')"
]))

# Cell 10: 3D 可视化
cells.append(md([
    "## Cell 10: 3D 轨迹可视化\n",
    "\n",
    "将拾取-递送运动轨迹绘制为 3D 图，按阶段分色标注。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 10: 3D 轨迹可视化\n",
    "# ============================================================\n",
    "\n",
    "PHASE_COLORS = {\n",
    "    'idle': '#808080', 'approach': '#2196F3', 'grasp': '#F44336',\n",
    "    'lift': '#FF9800', 'transit': '#9C27B0', 'deliver': '#4CAF50',\n",
    "    'return': '#607D8B',\n",
    "}\n",
    "PHASE_CN = {\n",
    "    'idle': '待机', 'approach': '接近', 'grasp': '抓取',\n",
    "    'lift': '提升', 'transit': '过渡', 'deliver': '递送', 'return': '返回',\n",
    "}\n",
    "\n",
    "\n",
    "def plot_trajectory_3d(trajectory, title='', ax=None):\n",
    "    show = ax is None\n",
    "    if ax is None:\n",
    "        fig = plt.figure(figsize=(10, 8))\n",
    "        ax = fig.add_subplot(111, projection='3d')\n",
    "\n",
    "    points = [point_to_cartesian(tp.raw_point) for tp in trajectory]\n",
    "\n",
    "    # 按阶段画线段\n",
    "    for i in range(len(points) - 1):\n",
    "        p1, p2 = points[i], points[i + 1]\n",
    "        phase = trajectory[i + 1].phase\n",
    "        color = PHASE_COLORS.get(phase, 'gray')\n",
    "        ax.plot([p1[0], p2[0]], [p1[1], p2[1]], [p1[2], p2[2]],\n",
    "               color=color, linewidth=2.5, alpha=0.8)\n",
    "\n",
    "    # 关键点标记\n",
    "    for tp, pt in zip(trajectory, points):\n",
    "        color = PHASE_COLORS.get(tp.phase, 'gray')\n",
    "        ms = 100 if tp.action else 50\n",
    "        mk = '*' if tp.action else 'o'\n",
    "        ax.scatter(*pt, c=color, s=ms, marker=mk, zorder=5,\n",
    "                  edgecolors='white', linewidths=0.5)\n",
    "        if tp.label:\n",
    "            ax.text(pt[0]+15, pt[1]+15, pt[2]+15, tp.label,\n",
    "                   fontsize=7, color=color)\n",
    "\n",
    "    # 器械托盘区域\n",
    "    tx = [-450, 150]; ty = [-750, -500]; tz = -50\n",
    "    verts = [[(tx[0],ty[0],tz),(tx[1],ty[0],tz),(tx[1],ty[1],tz),(tx[0],ty[1],tz)]]\n",
    "    ax.add_collection3d(Poly3DCollection(verts, alpha=0.15, facecolor='cyan', edgecolor='teal'))\n",
    "\n",
    "    ax.set_xlabel('X (mm)'); ax.set_ylabel('Y (mm)'); ax.set_zlabel('Z (mm)')\n",
    "    if title:\n",
    "        ax.set_title(title, fontsize=12)\n",
    "\n",
    "    if show:\n",
    "        from matplotlib.lines import Line2D\n",
    "        legend = [Line2D([0],[0], color=c, lw=2, label=PHASE_CN[p])\n",
    "                  for p, c in PHASE_COLORS.items()]\n",
    "        ax.legend(handles=legend, loc='upper left', fontsize=8)\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "\n",
    "\n",
    "# --- 单器械轨迹图 ---\n",
    "traj_tw = generate_full_trajectory(1, resolver_v2)\n",
    "plot_trajectory_3d(traj_tw, title='Tweezers - Full Pick-Deliver Trajectory')\n",
    "\n",
    "# --- 4 器械对比图 ---\n",
    "fig = plt.figure(figsize=(16, 12))\n",
    "for idx in range(4):\n",
    "    ax = fig.add_subplot(2, 2, idx + 1, projection='3d')\n",
    "    name = INSTRUMENT_MAP[str(idx)]\n",
    "    traj = generate_full_trajectory(idx, resolver_v2)\n",
    "    plot_trajectory_3d(traj, title=f'{name} (ID={idx})', ax=ax)\n",
    "    ax.view_init(elev=25, azim=-60)\n",
    "fig.suptitle('4 Instruments - Pick & Deliver Trajectories', fontsize=14, y=1.02)\n",
    "plt.tight_layout()\n",
    "plt.show()"
]))

# =====================================================================
# Part 3: 端到端演示
# =====================================================================
cells.append(md([
    "---\n",
    "# Part 3: 端到端流程演示\n",
    "\n",
    "## Cell 11: Mock 硬件层（夹爪、力传感器、日志）"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 11: Mock 硬件层\n",
    "# ============================================================\n",
    "\n",
    "class StepLogger:\n",
    "    ICONS = {\n",
    "        'voice': '\\U0001f3a4', 'llm': '\\U0001f9e0', 'lookup': '\\U0001f4cd',\n",
    "        'arm': '\\U0001f9be', 'grip': '\\u270a', 'force': '\\U0001f590',\n",
    "        'done': '\\u2705', 'error': '\\u274c', 'info': '\\u2139\\ufe0f',\n",
    "    }\n",
    "\n",
    "    def __init__(self):\n",
    "        self.steps = []\n",
    "        self._start = time.time()\n",
    "\n",
    "    def log(self, component, action, detail=''):\n",
    "        icon = self.ICONS.get(component, '')\n",
    "        self.steps.append({'t': time.time() - self._start,\n",
    "                           'component': component, 'action': action,\n",
    "                           'detail': detail, 'icon': icon})\n",
    "\n",
    "    def print_all(self):\n",
    "        for s in self.steps:\n",
    "            d = f\" - {s['detail']}\" if s['detail'] else ''\n",
    "            print(f\"  {s['icon']} [{s['component']:>6}] {s['action']}{d}\")\n",
    "\n",
    "    def reset(self):\n",
    "        self.steps.clear()\n",
    "        self._start = time.time()\n",
    "\n",
    "\n",
    "class MockGripper:\n",
    "    def __init__(self):\n",
    "        self.state = 'open'\n",
    "        self._qc = 0\n",
    "\n",
    "    def open_gripper(self, preset_id):\n",
    "        self.state = 'open'\n",
    "        return {'status': 'success', 'open_value': GRIPPER_PRESETS.get(preset_id, GRIPPER_PRESETS[-1])['open']}\n",
    "\n",
    "    def close_gripper(self, preset_id):\n",
    "        self.state = 'closed'\n",
    "        self._qc = 0\n",
    "        p = GRIPPER_PRESETS.get(preset_id, GRIPPER_PRESETS[-1])\n",
    "        return {'status': 'success', 'close_value': p['close'], 'force': p['force']}\n",
    "\n",
    "    def get_gripper_status(self):\n",
    "        self._qc += 1\n",
    "        return self._qc >= 2\n",
    "\n",
    "\n",
    "class MockForceSensor:\n",
    "    def __init__(self, delay_count=3):\n",
    "        self.enabled = False\n",
    "        self._qc = 0\n",
    "        self._delay = delay_count\n",
    "\n",
    "    def start_detection(self):\n",
    "        self.enabled = True\n",
    "        self._qc = 0\n",
    "\n",
    "    def stop_detection(self):\n",
    "        self.enabled = False\n",
    "\n",
    "    def get_force_status(self):\n",
    "        self._qc += 1\n",
    "        return {'enabled': self.enabled, 'is_applied': self._qc >= self._delay}\n",
    "\n",
    "\n",
    "print('Mock 硬件层已定义: StepLogger, MockGripper, MockForceSensor')"
]))

# Cell 12: MockRobotController
cells.append(md([
    "## Cell 12: MockRobotController（完整流程控制）\n",
    "\n",
    "对标 `RobotController.handler()` + `robotMove()`，v2 分支跳过 YOLO + 手眼标定。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 12: MockRobotController\n",
    "# 对标: bitRobot/service/RobotController.py\n",
    "# ============================================================\n",
    "\n",
    "class MockRobotController:\n",
    "    \"\"\"v2 固定位置模式控制器\"\"\"\n",
    "\n",
    "    def __init__(self, arm, gripper, force_sensor, resolver, logger):\n",
    "        self.arm = arm\n",
    "        self.gripper = gripper\n",
    "        self.force_sensor = force_sensor\n",
    "        self.resolver = resolver\n",
    "        self.logger = logger\n",
    "\n",
    "    def handler(self, task):\n",
    "        instrument_id = task.id\n",
    "        name = INSTRUMENT_MAP.get(str(instrument_id), '未知')\n",
    "        self.logger.log('info', f'开始执行: {task.msg_header}, id={instrument_id} ({name})')\n",
    "\n",
    "        try:\n",
    "            pos_info = self.resolver.resolve(instrument_id)\n",
    "        except ValueError as e:\n",
    "            self.logger.log('error', f'位置查表失败: {e}')\n",
    "            return False\n",
    "\n",
    "        self.logger.log('lookup', 'v2查表定位',\n",
    "                       f\"x={pos_info['x']}, y={pos_info['y']}, z={pos_info['z']}, rz={pos_info['rz']}\")\n",
    "        return self._robot_move(pos_info, instrument_id)\n",
    "\n",
    "    def _robot_move(self, pos_info, instrument_id):\n",
    "        x, y, z, rz = pos_info['x'], pos_info['y'], pos_info['z'], pos_info['rz']\n",
    "        name = pos_info['name']\n",
    "\n",
    "        # 预开夹爪\n",
    "        self.gripper.open_gripper(instrument_id)\n",
    "        self.logger.log('grip', '预开夹爪', f'preset_id={instrument_id}')\n",
    "\n",
    "        # 阶段1: 接近抓取 (对标 robotMove line 71-84)\n",
    "        self.logger.log('arm', '阶段1-接近', '悬停 -> 下降')\n",
    "        self.arm.set_phase('approach', '悬停')\n",
    "        self.arm.execute_path([[x, y, z+Z_HOVER, FIXED_RX, FIXED_RY, rz, 0]])\n",
    "        self.arm.set_phase('grasp', '抓取')\n",
    "        self.arm.execute_path([[x, y, z+Z_GRASP, FIXED_RX, FIXED_RY, rz, 0]])\n",
    "\n",
    "        # 夹取\n",
    "        result = self.gripper.close_gripper(instrument_id)\n",
    "        self.logger.log('grip', '夹爪闭合', f\"force={result['force']}\")\n",
    "        while not self.gripper.get_gripper_status():\n",
    "            pass\n",
    "        self.logger.log('arm', f'已抓取{name}')\n",
    "\n",
    "        # 阶段2: 递送 (对标 robotMove line 102-113)\n",
    "        self.logger.log('arm', '阶段2-递送', '提升 -> 复位 -> 递送')\n",
    "        self.arm.set_phase('lift', '提升')\n",
    "        self.arm.execute_path([[x, y, z+Z_HOVER, FIXED_RX, FIXED_RY, rz, 0]])\n",
    "        self.arm.set_phase('transit', '过渡')\n",
    "        self.arm.execute_path([RESET_POINT])\n",
    "        self.arm.set_phase('deliver', '递送')\n",
    "        self.arm.execute_path([TARGET_POINT])\n",
    "        self.logger.log('arm', '已到达递送位置')\n",
    "\n",
    "        # 阶段3: 力检测 -> 释放 -> 复位 (对标 robotMove line 118-155)\n",
    "        self.force_sensor.start_detection()\n",
    "        self.logger.log('force', '开启力检测', '等待医生取走器械...')\n",
    "        while True:\n",
    "            if self.force_sensor.get_force_status()['is_applied']:\n",
    "                break\n",
    "        self.logger.log('force', '检测到外力', '松开夹爪')\n",
    "        self.gripper.open_gripper(-1)\n",
    "        self.force_sensor.stop_detection()\n",
    "        self.logger.log('arm', f'{name}已被取走')\n",
    "\n",
    "        self.logger.log('arm', '阶段3-复位', '返回预备姿态')\n",
    "        self.arm.set_phase('return', '最终复位')\n",
    "        self.arm.execute_path([RESET_POINT])\n",
    "        self.logger.log('done', '已恢复到预备姿态')\n",
    "        return True\n",
    "\n",
    "\n",
    "print('MockRobotController 已定义')"
]))

# Cell 13: PipelineRunner
cells.append(md([
    "## Cell 13: PipelineRunner（流程编排引擎）\n",
    "\n",
    "组装所有组件，提供 `run(voice_text)` 一键执行完整流程。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 13: PipelineRunner\n",
    "# ============================================================\n",
    "\n",
    "class PipelineRunner:\n",
    "    def __init__(self):\n",
    "        self.config_loader = ConfigLoader(INSTRUMENTS_INI_CONTENT)\n",
    "        self.llm = MockLLMService(self.config_loader)\n",
    "        self.resolver = PositionResolver(self.config_loader)\n",
    "        self.arm = MockRobotArm()\n",
    "        self.gripper = MockGripper()\n",
    "        self.force_sensor = MockForceSensor(delay_count=3)\n",
    "        self.logger = StepLogger()\n",
    "        self.controller = MockRobotController(\n",
    "            self.arm, self.gripper, self.force_sensor, self.resolver, self.logger\n",
    "        )\n",
    "\n",
    "    def run(self, voice_text, show_trajectory=False):\n",
    "        self.logger.reset()\n",
    "        self.arm.clear_trajectory()\n",
    "\n",
    "        self.logger.log('voice', '语音输入', voice_text)\n",
    "\n",
    "        result = self.llm.process_cmd_text(voice_text)\n",
    "        if isinstance(result, str):\n",
    "            task = TaskInfo(msg_header=result, id=-1)\n",
    "        else:\n",
    "            if result[1] == -1:\n",
    "                self.logger.log('llm', '解析结果', '语音不包含医疗器械，停止后续操作')\n",
    "                self.logger.log('error', '流程终止')\n",
    "                self._print_result()\n",
    "                return {'success': False, 'logs': self.logger.steps}\n",
    "            task = TaskInfo(msg_header=result[0], id=result[1])\n",
    "\n",
    "        name = INSTRUMENT_MAP.get(str(task.id), task.msg_header)\n",
    "        self.logger.log('llm', 'LLM解析', f'{task.msg_header}, id={task.id} ({name})')\n",
    "\n",
    "        success = False\n",
    "        if task.msg_header == '器件':\n",
    "            success = self.controller.handler(task)\n",
    "        elif task.msg_header == '统计':\n",
    "            self.logger.log('info', '执行统计', '扫描所有槽位...')\n",
    "            all_inst = self.config_loader.get_all()\n",
    "            summary = ', '.join([f'{v.name}: 槽位{k}' for k, v in all_inst.items()])\n",
    "            self.logger.log('done', f'统计完成: 共{len(all_inst)}种器械', summary)\n",
    "            success = True\n",
    "        elif task.msg_header == '清点':\n",
    "            self.logger.log('info', '执行清点', '对比基准数据...')\n",
    "            self.logger.log('done', '清点完成: 所有器械数量匹配')\n",
    "            success = True\n",
    "        elif task.msg_header == '取消':\n",
    "            self.logger.log('info', '执行取消', '停止当前操作')\n",
    "            self.logger.log('done', '已恢复到预备姿态')\n",
    "            success = True\n",
    "\n",
    "        self._print_result()\n",
    "        if show_trajectory and self.arm.get_trajectory():\n",
    "            plot_trajectory_3d(self.arm.get_trajectory(), title=f'{name} - 运动轨迹')\n",
    "\n",
    "        return {'success': success, 'logs': self.logger.steps,\n",
    "                'trajectory': self.arm.get_trajectory()}\n",
    "\n",
    "    def _print_result(self):\n",
    "        print('\\n' + '=' * 50)\n",
    "        print('流程执行日志:')\n",
    "        print('=' * 50)\n",
    "        self.logger.print_all()\n",
    "        print('=' * 50)\n",
    "\n",
    "\n",
    "# --- 快速验证 ---\n",
    "pipeline = PipelineRunner()\n",
    "pipeline.run('传递镊子', show_trajectory=True)"
]))

# Cell 14: 交互式演示
cells.append(md([
    "## Cell 14: 交互式演示\n",
    "\n",
    "输入语音文本，观察完整的模拟流程。\n",
    "\n",
    "**试试输入**: `传递镊子` / `给我剪刀` / `刀柄` / `持针钳` / `统计` / `清点` / `取消` / `你好`"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 14: 交互式演示\n",
    "# ============================================================\n",
    "\n",
    "pipeline = PipelineRunner()\n",
    "\n",
    "print('v2 固定位置模式 - 交互式演示')\n",
    "print('支持指令: 器械名称(刀柄/镊子/剪刀/持针钳) / 统计 / 清点 / 取消')\n",
    "print('输入 q 退出\\n')\n",
    "\n",
    "while True:\n",
    "    voice = input('请输入语音指令: ')\n",
    "    if voice.strip().lower() == 'q':\n",
    "        print('退出演示')\n",
    "        break\n",
    "    if not voice.strip():\n",
    "        continue\n",
    "    result = pipeline.run(voice.strip(), show_trajectory=True)\n",
    "    print()"
]))

# Cell 15: 时序图
cells.append(md([
    "## Cell 15: 流程时序图\n",
    "\n",
    "将执行流程可视化为甘特图风格的时序图。"
]))

cells.append(code([
    "# ============================================================\n",
    "# Cell 15: 流程时序图\n",
    "# ============================================================\n",
    "\n",
    "def plot_timeline(logs, title='流程时序图'):\n",
    "    if not logs:\n",
    "        print('无日志数据')\n",
    "        return\n",
    "\n",
    "    comp_labels = {\n",
    "        'voice': '语音输入', 'llm': 'LLM解析', 'lookup': '位置查表',\n",
    "        'arm': '机械臂', 'grip': '夹爪', 'force': '力传感器',\n",
    "        'done': '完成', 'error': '错误', 'info': '系统',\n",
    "    }\n",
    "    comp_colors = {\n",
    "        'voice': '#FF9800', 'llm': '#9C27B0', 'lookup': '#2196F3',\n",
    "        'arm': '#4CAF50', 'grip': '#F44336', 'force': '#00BCD4',\n",
    "        'done': '#8BC34A', 'error': '#F44336', 'info': '#607D8B',\n",
    "    }\n",
    "\n",
    "    seen = []\n",
    "    for log in logs:\n",
    "        if log['component'] not in seen:\n",
    "            seen.append(log['component'])\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(14, max(3, len(seen) * 0.6 + 1)))\n",
    "    y_map = {c: i for i, c in enumerate(reversed(seen))}\n",
    "\n",
    "    for i, log in enumerate(logs):\n",
    "        comp = log['component']\n",
    "        y = y_map[comp]\n",
    "        color = comp_colors.get(comp, 'gray')\n",
    "        ax.barh(y, width=0.8, left=i, height=0.5, color=color, alpha=0.8, edgecolor='white')\n",
    "        action_short = log['action'][:12]\n",
    "        ax.text(i + 0.4, y, action_short, ha='center', va='center',\n",
    "               fontsize=6, color='white', fontweight='bold')\n",
    "\n",
    "    ax.set_yticks(range(len(seen)))\n",
    "    ax.set_yticklabels([comp_labels.get(c, c) for c in reversed(seen)], fontsize=10)\n",
    "    ax.set_xlabel('Steps', fontsize=10)\n",
    "    ax.set_title(title, fontsize=13)\n",
    "    ax.set_xlim(-0.5, len(logs) + 0.5)\n",
    "    ax.grid(axis='x', alpha=0.3)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "\n",
    "# --- 运行 4 种器械并绘制时序图 ---\n",
    "for inst_name in ['刀柄', '镊子', '剪刀', '持针钳']:\n",
    "    pv = PipelineRunner()\n",
    "    result = pv.run(inst_name, show_trajectory=False)\n",
    "    plot_timeline(result['logs'], title=f'{inst_name} - Timeline')\n",
    "\n",
    "print('\\n所有器械流程时序图绘制完成')"
]))

# =====================================================================
# Write notebook
# =====================================================================
output_path = os.path.join(os.path.dirname(__file__) if '__file__' in dir() else '.', 'v2_simulation.ipynb')
# Use fixed path
output_path = r"D:\2026-Qoder\医疗机器人代码\RobotServer\notebooks\v2_simulation.ipynb"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Notebook 已生成: {output_path}")
print(f"共 {len(cells)} 个 Cell ({sum(1 for c in cells if c['cell_type']=='code')} code + "
      f"{sum(1 for c in cells if c['cell_type']=='markdown')} markdown)")
